//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sustent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int id { get; set; }
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Display(Name = "Senha")]
        [Required(ErrorMessage = "Informe a sua senha", AllowEmptyStrings = false)]
        public string senha { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Informe o seu e-mail", AllowEmptyStrings = false)]
        public string email { get; set; }
        [Display(Name = "Login")]
        public string login { get; set; }
    }
}
